services:
    goesg-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: goesg-api
        ports:
            - "8000:8000"
        environment:
            INFISICAL_ENV: ${INFISICAL_ENV}
            INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
            INFISICAL_CLIENT_SECRET: ${INFISICAL_CLIENT_SECRET}
            INFISICAL_CLIENT_ID: ${INFISICAL_CLIENT_ID}
        volumes:
            - ./logs:/app/logs
        restart: unless-stopped
